version: 4.0.{build}
configuration: Release
os: Visual Studio 2019

environment:
  nodejs_version: "12.13.1"
  typescript_version: "3.0.1"
  github_auth_token:
    secure: H/7uCrjmWHGJxgN3l9fbhhdVjvvWI8VVF4ZzQqeXuJwAf+PgSNBdxv4SS+rMQ+RH


    
# Do not build on tags (GitHub and BitBucket)
skip_tags: true

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

#  - cmd: set path=%programfiles(x86)%\\Microsoft SDKs\TypeScript\3.6;%path%
#  - cmd: tsc -v
build_script:
  - ps: |
      $deployBranches =
        "feature/v4",
        "develop",
        "master";

      If(($env:APPVEYOR_REPO_BRANCH -in $deployBranches -Or $env:APPVEYOR_REPO_COMMIT_MESSAGE -Match '!deploy') -And $env:APPVEYOR_REPO_COMMIT_MESSAGE -NotMatch '!build') {
        Write-Output "This is a deployment build"
        $env:Deploy = 'true'
        ./build.ps1
      }
      Else 
      {
        $env:Deploy = 'false'
        Write-Output "This is a not a deployment build"
        ./build.ps1 --target=build
      }   

skip_commits:
  files:
    - '**/*.md'
 
after_build:
- ps: |
    $deployBranches =
        "feature/v4",
        "develop",
        "master";

    If(($env:APPVEYOR_REPO_BRANCH -in $deployBranches -Or $env:APPVEYOR_REPO_COMMIT_MESSAGE -Match '!deploy') -And $env:APPVEYOR_REPO_COMMIT_MESSAGE -NotMatch '!build') 
    {
      Write-Output "Deploying!"
      Get-ChildItem -Recurse .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      Get-ChildItem -Recurse .\*.gz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
    }
    Else 
    {
      Write-Output "No Deployment"
    }

#cache:
#- '%USERPROFILE%\.nuget\packages'
deploy:
- provider: GitHub
  release: Ombi v$(appveyor_build_version)
  auth_token:
    secure: jDpp1/WUQl3uN41fNI3VeZoRZbDiDfs3GPQ1v+C5ZNE3cWdnUvuJfCCfUbYUV1Rp
  draft: true
  on:
    branch: master
